# Task 1:

1.
Write a function to compute 5/0 and use try/except to catch the exceptions.

In [11]:
def divide():
    return 5/0
try:
    divide()
except:
    print('Division by zero')

Division by zero


2.
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [12]:
subjects = ['Americans','Indians']
verbs = ['Play', 'watch']
objects = ['Baseball','Cricket']

for i in subjects:
    for j in verbs:
        for k in objects:
            print(i+" "+j+" "+k)

Americans Play Baseball
Americans Play Cricket
Americans watch Baseball
Americans watch Cricket
Indians Play Baseball
Indians Play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2:

1.
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [13]:
import numpy as np

def vander_matrix(vector, n, increasing=False):
    if increasing:
        matrix = np.array([x**i for x in vector for i in range(n)]).reshape(vector.size,n)
    elif not increasing:
        matrix = np.array([x**(n-1-i) for x in vector for i in range(n)]).reshape(vector.size,n)
    return matrix

input_vector = np.array([1,3,4,6,7,10])
matrix_dec = vander_matrix(input_vector,6,False)
matrix_inc = vander_matrix(input_vector,6,True)

print("Vander matrix decreasing order:\n\n",matrix_dec,"\n")
print("Vander matrix in increasing order:\n\n",matrix_inc,"\n")


Vander matrix decreasing order:

 [[     1      1      1      1      1      1]
 [   243     81     27      9      3      1]
 [  1024    256     64     16      4      1]
 [  7776   1296    216     36      6      1]
 [ 16807   2401    343     49      7      1]
 [100000  10000   1000    100     10      1]] 

Vander matrix in increasing order:

 [[     1      1      1      1      1      1]
 [     1      3      9     27     81    243]
 [     1      4     16     64    256   1024]
 [     1      6     36    216   1296   7776]
 [     1      7     49    343   2401  16807]
 [     1     10    100   1000  10000 100000]] 

